# Generated by Django 5.1.6 on 2025-02-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movi_app', '0002_review_stars_alter_review_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='title',
        ),
    ]
