# Generated by Django 5.1.6 on 2025-02-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi_app', '0004_remove_review_title_review_text_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=5, null=True),
        ),
    ]
